### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by ismaelxyz** [zhengxyz123/mystery#1]
(myenv) user@debian:~/Documents/mystery$ python -m mystery
Traceback (most recent call last):
  File "/home/use/Documents/mystery/mystery/__main__.py", line 45, in start
    app.run()
  File "/home/user/Documents/mystery/myenv/lib/python3.12/site-packages/pyglet/app/__init__.py", line 76, in run
    event_loop.run(interval)
  File "/home/user/Documents/mystery/myenv/lib/python3.12/site-packages/pyglet/app/base.py", line 163, in run
    timeout = self.idle()
              ^^^^^^^^^^^
  File "/home/user/Documents/mystery/myenv/lib/python3.12/site-packages/pyglet/app/base.py", line 224, in idle
    self.clock.call_scheduled_functions(dt)
  File "/home/user/Documents/mystery/myenv/lib/python3.12/site-packages/pyglet/clock.py", line 217, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/home/user/Documents/mystery/mystery/scene/menu.py", line 86, in _animate
    self.window.switch_scene("start")
  File "/home/user/Documents/mystery/mystery/scene/__init__.py", line 105, in switch_scene
    self._scenes[self._now].dispatch_event("on_resize", self.width, self.height)
  File "/home/user/Documents/mystery/myenv/lib/python3.12/site-packages/pyglet/event.py", line 387, in dispatch_event
    if getattr(self, event_type)(*args):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Documents/mystery/mystery/scene/start.py", line 62, in on_resize
    self.message.resize()
  File "/home/user/Documents/mystery/mystery/gui/widgets/message_box.py", line 88, in resize
    text = utils.line_break_func(self._text, self._label.width)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Documents/mystery/mystery/utils.py", line 45, in line_break_func
    if (func := resmgr.info("line_break_func")) in lang2func:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Documents/mystery/mystery/resource/manager.py", line 96, in info
    return self._translation_now["language.info"].get(key, "")
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'language.info'

**Comment by zhengxyz123** [comment]
Thank you for open this issue.

This error will be triggered when your language code isn't support.

It's fixed now.
